source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UIViewFadeAnimationExtension_Example', :exclusive => true do
  pod 'UIViewFadeAnimationExtension', :path => '../'
end

target 'UIViewFadeAnimationExtension_Tests', :exclusive => true do
  pod 'UIViewFadeAnimationExtension', :path => '../'

  
end
